//benefit of a single page application.
/* 
1. easy to load 
2. better user experience.
3. Quick Loading Time. ...
4. Seamless User Experience. ...
5. ase in Building Feature-rich Apps. ...
6. Uses Less Bandwidth. ...
7. Doesn't Perform Well With SEO. ...
8. Uses a Lot of Browser Resources. ...
9. Security Issues.

 */